[package]
name = "toy-rdbms"
version = "0.1.0"
authors = ["daisuzz <daisaku.rugby@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
anyhow = "1.0"

[dev-dependencies]
tempfile = "3.2.0"
